# Generated by Django 2.0.5 on 2018-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='URLfoto',
        ),
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default='null', upload_to='../img/articulos'),
            preserve_default=False,
        ),
    ]
