# Generated by Django 2.0.5 on 2018-05-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0002_auto_20180505_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
