# Generated by Django 2.0.5 on 2018-06-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0003_auto_20180621_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='URLfoto',
        ),
        migrations.AddField(
            model_name='espacio',
            name='image',
            field=models.ImageField(default=1, upload_to='../img/espacios'),
            preserve_default=False,
        ),
    ]
