# Generated by Django 2.0.5 on 2018-05-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0003_auto_20180505_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
