# Generated by Django 2.0.5 on 2018-05-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0004_auto_20180505_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
