# Generated by Django 2.0.3 on 2018-05-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0005_auto_20180505_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Vigente', 'Vigente'), ('Caducado', 'Caducado'), ('Perdido', 'Perdido')], default='Vigente', max_length=50),
        ),
    ]
