# Generated by Django 2.0.5 on 2018-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0005_auto_20180505_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='descripcion',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='URLfoto',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='lista_tags',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='articulo',
            name='name',
            field=models.CharField(default='Articulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='photo',
            field=models.ImageField(default='Articulo', upload_to='../img/articulos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='status',
            field=models.CharField(default='Articulo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='tags',
            field=models.CharField(default='Articulo', max_length=50),
            preserve_default=False,
        ),
    ]
