# Generated by Django 2.0.3 on 2018-05-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0007_auto_20180518_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='tipo_objeto',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_objeto',
            field=models.CharField(choices=[('Artículo', 'Artículo'), ('Espacio', 'Espacio')], default='Artículo', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hab',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], default='Habilitado', max_length=50),
        ),
    ]
