# Generated by Django 2.0.3 on 2018-05-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0011_auto_20180527_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='rut',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='inventarioCEI.Profile'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='inventarioCEI.Profile'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50),
        ),
    ]
