# Generated by Django 2.0.3 on 2018-05-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0012_auto_20180530_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarioCEI.Profile'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarioCEI.Profile'),
        ),
    ]
