# Generated by Django 2.0.3 on 2018-06-04 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventarioCEI', '0013_auto_20180530_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='user',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='id_objeto',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='tipo_objeto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_objeto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo_objeto',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='content_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
