# Generated by Django 2.0.3 on 2018-06-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0015_auto_20180604_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'inventarioCEI'), ('model', 'articulo')), models.Q(('app_label', 'inventarioCEI'), ('model', 'espacio')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'inventarioCEI'), ('model', 'articulo')), models.Q(('app_label', 'inventarioCEI'), ('model', 'espacio')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
