# Generated by Django 2.0.3 on 2018-06-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0016_auto_20180605_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En préstamo', 'En préstamo'), ('En reparación', 'En reparación'), ('Perdido', 'Perdido')], default='Disponible', max_length=50),
        ),
    ]
