# Generated by Django 2.0.3 on 2018-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0017_auto_20180621_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En préstamo', 'En préstamo'), ('En reparación', 'En reparación')], default='Disponible', max_length=50),
        ),
    ]
