# Generated by Django 2.0.3 on 2018-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioCEI', '0018_auto_20180621_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='URLfoto',
        ),
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default=1, upload_to='../img/articulos'),
            preserve_default=False,
        ),
    ]
